# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_reuse_count', models.IntegerField()),
                ('ip_reuse_count', models.IntegerField()),
                ('address_cluster_size', models.IntegerField()),
                ('shared_phone_count', models.IntegerField()),
                ('velocity_flag', models.BooleanField()),
                ('synthetic_id_flag', models.BooleanField()),
                ('fraud_risk_score', models.FloatField()),
                ('fraud_risk_label', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('recommended_action', models.CharField(choices=[('pass', 'Pass'), ('manual_review', 'Manual Review'), ('reject', 'Reject'), ('watchlist', 'Watchlist')], max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
