# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_lender', models.CharField(choices=[('northern_arc', 'Northern Arc'), ('idfc_first', 'IDFC First Bank'), ('ujjivan_sfb', 'Ujjivan Small Finance Bank'), ('suryoday_sfb', 'Suryoday Small Finance Bank'), ('trillion_loans', 'Trillion Loans'), ('grow_money', 'Grow Money Capital'), ('uco_bank', 'UCO Bank'), ('indian_bank', 'Indian Bank')], max_length=20)),
                ('approval_probability', models.FloatField()),
                ('expected_yield', models.FloatField()),
                ('objective_score', models.FloatField()),
                ('fallback_lender', models.CharField(choices=[('northern_arc', 'Northern Arc'), ('idfc_first', 'IDFC First Bank'), ('ujjivan_sfb', 'Ujjivan Small Finance Bank'), ('suryoday_sfb', 'Suryoday Small Finance Bank'), ('trillion_loans', 'Trillion Loans'), ('grow_money', 'Grow Money Capital'), ('uco_bank', 'UCO Bank'), ('indian_bank', 'Indian Bank')], max_length=20)),
                ('lender_response', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending')], max_length=15)),
                ('actual_rate', models.FloatField(null=True)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
