# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('dob_extracted', models.DateField()),
                ('name_extracted', models.CharField(max_length=120)),
                ('address_extracted', models.TextField()),
                ('name_match_score', models.FloatField()),
                ('dob_match', models.BooleanField()),
                ('bureau_pulled', models.BooleanField(default=False)),
                ('bureau_score', models.IntegerField(null=True)),
                ('bureau_source', models.CharField(choices=[('CRIF', 'CRIF'), ('Experian', 'Experian'), ('no_hit', 'No Hit')], max_length=20)),
                ('kyc_status', models.CharField(choices=[('clear', 'Clear'), ('review', 'Needs Review'), ('rejected', 'Rejected')], max_length=15)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
