# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_completed', models.IntegerField()),
                ('on_time_payment_rate', models.FloatField()),
                ('browse_events_last_30d', models.IntegerField()),
                ('upgrade_probability', models.FloatField()),
                ('upgrade_score_band', models.CharField(max_length=10)),
                ('recommended_bike', models.CharField(max_length=30)),
                ('estimated_new_emi', models.IntegerField()),
                ('emi_delta', models.IntegerField()),
                ('trigger_channel', models.CharField(max_length=20)),
                ('offer_message', models.TextField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
