# Generated by Django 5.1.4 on 2026-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('city', models.CharField(choices=[('BLR', 'Bangalore'), ('DEL', 'Delhi'), ('PUN', 'Pune'), ('HYD', 'Hyderabad'), ('MUM', 'Mumbai'), ('CHN', 'Chennai'), ('IND', 'Indore'), ('JPR', 'Jaipur')], max_length=3)),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self-Employed'), ('gig', 'Gig Worker'), ('student', 'Student')], max_length=20)),
                ('monthly_income', models.IntegerField()),
                ('bike_model', models.CharField(choices=[('hero_splendor', 'Hero Splendor Plus XTEC'), ('honda_activa', 'Honda Activa 125'), ('suzuki_access', 'Suzuki Access 125'), ('re_meteor', 'Royal Enfield Meteor 350'), ('ola_s1x', 'Ola S1 X 2kWh'), ('ather_450x', 'Ather 450X'), ('bajaj_pulsar', 'Bajaj Pulsar N160'), ('tvs_ntorq', 'TVS NTorq 125')], max_length=30)),
                ('bike_price', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('tenure_months', models.IntegerField()),
                ('down_payment_pct', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('lead_scored', models.BooleanField(default=False)),
                ('kyc_done', models.BooleanField(default=False)),
                ('underwritten', models.BooleanField(default=False)),
                ('routed', models.BooleanField(default=False)),
                ('fraud_checked', models.BooleanField(default=False)),
                ('disbursed', models.BooleanField(default=False)),
            ],
        ),
    ]
