# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_minutes', models.FloatField()),
                ('emi_calc_used', models.BooleanField()),
                ('models_viewed', models.IntegerField()),
                ('return_visit', models.BooleanField()),
                ('utm_source', models.CharField(max_length=30)),
                ('propensity_score', models.FloatField()),
                ('score_band', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
