# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpd_30_prob', models.FloatField()),
                ('dpd_60_prob', models.FloatField()),
                ('dpd_90_prob', models.FloatField()),
                ('risk_bucket', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('recommended_channel', models.CharField(max_length=20)),
                ('generated_message', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('emi_amount', models.IntegerField()),
                ('paid_on_time', models.BooleanField()),
                ('days_past_due', models.IntegerField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
