# Generated by Django 5.1.4 on 2026-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_monthly_avg', models.IntegerField()),
                ('upi_volatility', models.FloatField()),
                ('telecom_tenure_yrs', models.FloatField()),
                ('gst_filed', models.BooleanField()),
                ('pd_score', models.FloatField()),
                ('risk_grade', models.CharField(max_length=3)),
                ('recommended_ltv', models.FloatField()),
                ('recommended_rate', models.FloatField()),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('review', 'Manual Review'), ('reject', 'Reject')], max_length=15)),
                ('shap_json', models.TextField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
